### ISSUE TITLE
Error parsing the power_data.json from Scaphandre

### ISSUE THREAD

**Issue by lcanagui** [Boavizta/boagent#49]
Hello,

I get this error with the 0.0.8 of boagent:

`File "/home/boagent/./boagent/api/api.py", line 193, in metrics
    get_metrics(
  File "/home/boagent/./boagent/api/api.py", line 467, in get_metrics
    power_data = get_power_data(start_time, end_time)
  File "/home/boagent/./boagent/api/api.py", line 605, in get_power_data
    data = json.loads(formatted_data)
  File "/usr/local/lib/python3.10/json/init.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3292 (char 3291)`

It may be a problem while parsing this power_data.json generated by Scaphandre.
[power_data.json](https://github.com/Boavizta/boagent/files/15223295/power_data.json)

**Comment by bdromard** [comment]
Hello @lcanagui !

I just tried to recreate the bug by querying the Boagent API (through the `/query` endpoint), and indeed I got the same error as yours with the latest `docker-compose` version for Boagent. Turned out the Docker image for `scaphandre:dev` I was using was an old version. After deleting it and downloading the latest Scaphandre Docker image (`hubblo/scaphandre:dev`), I get a 200 OK response from the Boagent API.

If you were using Boagent in a similar way, could you check your version of the Scaphandre Docker image you are using, delete it and download its latest version ?

Thanks in advance!

**Comment by demeringo** [comment]
Hi @bdromard and thank you.

We are now using scaphandre:dev

I mention another issue here (as this is likely related to @lcanagui tests as we are using the same physical host and account).
I noticed that we have to run the scaph container in privileged mode to access the powercap files.

https://github.com/hubblo-org/scaphandre/issues/386
